DataSource:
  mySQLColumnName: username
  mySQLTablename: authme
  mySQLUsername: dannyly
  backend: mysql
  mySQLColumnLastLogin: lastlogin
  mySQLDatabase: howtocash
  mySQLPort: '3306'
  mySQLColumnIp: ip
  mySQLHost: 27.118.30.105
  mySQLColumnPassword: password
  mySQLPassword: HQMfqPhMtzwyZ9NX
  caching: true
  mySQLlastlocX: x
  mySQLlastlocY: y
  mySQLlastlocZ: z
  mySQLlastlocWorld: world
  mySQLColumnEmail: email
  mySQLColumnId: id
  mySQLColumnLogged: isLogged
GroupOptions:
  UnregisteredPlayerGroup: ''
  RegisteredPlayerGroup: ''
  Permissions:
    PermissionsOnJoin: []
settings:
  sessions:
    enabled: false
    timeout: 10
    sessionExpireOnIpChange: false
  restrictions:
    allowChat: false
    allowCommands:
    - /dangnhap
    - /dangky
    - /dn
    - /dk
    - /passpartu
    - /email
    - /captcha
    maxRegPerIp: 10
    maxNicknameLength: 20
    ForceSingleSession: true
    ForceSpawnLocOnJoinEnabled: true
    SaveQuitLocation: false
    AllowRestrictedUser: false
    AllowedRestrictedUser:
    - playername;127.0.0.1
    kickNonRegistered: false
    kickOnWrongPassword: true
    teleportUnAuthedToSpawn: true
    minNicknameLength: 3
    allowMovement: false
    timeout: 60
    allowedNicknameCharacters: '[a-zA-Z0-9_]*'
    allowedMovementRadius: 100
    enablePasswordVerifier: true
    ProtectInventoryBeforeLogIn: true
    displayOtherAccounts: true
    ForceSpawnOnTheseWorlds:
    - world
    - world_nether
    - world_the_end
    banUnsafedIP: false
    spawnPriority: authme,essentials,multiverse,default
    maxLoginPerIp: 0
    maxJoinPerIp: 0
    noTeleport: false
    allowedPasswordCharacters: '[\x21-\x7E]*'
  GameMode:
    ForceSurvivalMode: true
    ResetInventoryIfCreative: false
    ForceOnlyAfterLogin: false
  security:
    minPasswordLength: 4
    unLoggedinGroup: unLoggedinGroup
    passwordHash: SHA256
    doubleMD5SaltLength: 8
    supportOldPasswordHash: false
    unsafePasswords: []
  registration:
    enabled: true
    messageInterval: 5
    force: true
    enableEmailRegistrationSystem: false
    doubleEmailCheck: false
    forceKickAfterRegister: true
    forceLoginAfterRegister: true
  unrestrictions:
    UnrestrictedName: []
  messagesLanguage: en
  forceCommands: []
  useWelcomeMessage: true
  broadcastWelcomeMessage: true
  forceCommandsAsConsole: []
  delayJoinMessage: false
  applyBlindEffect: false
  forceRegisterCommands: []
  forceRegisterCommandsAsConsole: []
ExternalBoardOptions:
  mySQLColumnSalt: ''
  mySQLColumnGroup: ''
  nonActivedUserGroup: -1
  mySQLOtherUsernameColumns: []
  bCryptLog2Round: 10
  phpbbTablePrefix: phpbb_
  phpbbActivatedGroupId: 2
  wordpressTablePrefix: wp_
permission:
  EnablePermissionCheck: false
BackupSystem:
  ActivateBackup: false
  OnServerStart: false
  OnServerStop: true
  MysqlWindowsPath: C:\\Program Files\\MySQL\\MySQL Server 5.1\\
Passpartu:
  enablePasspartu: false
Security:
  SQLProblem:
    stopServer: true
  ReloadCommand:
    useReloadCommandSupport: true
  console:
    noConsoleSpam: false
    removePassword: true
    logConsole: false
  captcha:
    useCaptcha: false
    maxLoginTry: 5
    captchaLength: 5
Converter:
  Rakamak:
    fileName: users.rak
    useIP: false
    ipFileName: UsersIp.rak
  CrazyLogin:
    fileName: accounts.db
Email:
  mailSMTP: smtp.gmail.com
  mailPort: 465
  mailAccount: justmc.net@gmail.com
  mailPassword: Danks76429
  mailSenderName: JustMine Server
  RecoveryPasswordLength: 8
  mailSubject: Mat khau moi cua ban
  maxRegPerEmail: 1
  recallPlayers: false
  delayRecall: 5
  mailText: 'Than gui <playername>, <br /><br /> Day la mat khau moi cua ban trong
    JustMine : <br /><br /> <generatedpass><br /><br />Nho doi mat khau dang nhap
    bang lenh <br /> /changepassword <generatedpass> matkhaumoi'
  emailBlacklisted: []
  emailWhitelisted: []
  generateImage: true
Hooks:
  multiverse: true
  chestshop: true
  bungeecord: true
  disableSocialSpy: true
  useEssentialsMotd: false
  customAttributes: false
Performances: {}
Purge:
  useAutoPurge: false
  daysBeforeRemovePlayer: 60
  removePlayerDat: false
  removePermissions: false
Protection:
  enableProtection: false
  countries:
  - US
  - GB
  enableAntiBot: false
  antiBotSensibility: 5
  antiBotDuration: 10
  countriesBlacklist:
  - A1
VeryGames:
  enableIpCheck: false
